remote: origin
target-branch: main
chart-dirs:
- ./
helm-extra-set-args:
  ## Removed when images of TOA and setupapp are released to public registries 
  setupApp:
    image: 
      repository: nginx
    persistence:
      storageClassName: standard
    environmentVariables:
      mgmtPrivateKey: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
      mgmtPublicKey: |
          -----BEGIN PUBLIC KEY-----
          -----END PUBLIC KEY-----
  trustedOutputApp:
    image: 
      repository: nginx
    persistence:
      storageClassName: standard
    environmentVariables:
      mgmtPrivateKey: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
      mgmtPublicKey: |
          -----BEGIN PUBLIC KEY-----
          -----END PUBLIC KEY-----