remote: origin
target-branch: main
chart-dirs:
- ./
helm-extra-set-args:
  ## Removed when images of TOA and setupapp are released to public registries 
  setupApp.image.repository: nginx
  setupApp.image.tag: latest
  setupApp.persistence.storageClassName: standard
  setupApp.environmentVariables.mgmtPrivateKey: "-----BEGIN PRIVATE KEY-----Test-----END PRIVATE KEY-----"
            
  setupApp.environmentVariables.mgmtPublicKey:  "-----BEGIN PRIVATE KEY-----Test-----END PRIVATE KEY-----"
  trustedOutputApp.image.repository: nginx
  trustedOutputApp.image.tag: latest
  trustedOutputApp.persistence.storageClassName: standard
  trustedOutputApp.environmentVariables.mgmtPrivateKey: "-----BEGIN PRIVATE KEY-----Test-----END PRIVATE KEY-----"
  trustedOutputApp.environmentVariables.mgmtPublicKey: "-----BEGIN PRIVATE KEY-----Test-----END PRIVATE KEY-----"