remote: origin
target-branch: main
chart-dirs:
- ./
helm-extra-set-args:
  setupApp.image.repository: nginx
  setupApp.image.tag: latest
  setupApp.persistence.storageClassName: standard
  setupApp.environmentVariables.mgmtPrivateKey: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
  setupApp.environmentVariables.mgmtPublicKey: |
    -----BEGIN PUBLIC KEY-----
    -----END PUBLIC KEY-----
  trustedOutputApp.image.repository: nginx
  trustedOutputApp.image.tag: latest
  trustedOutputApp.persistence.storageClassName: standard
  trustedOutputApp.environmentVariables.mgmtPrivateKey: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
  trustedOutputApp.environmentVariables.mgmtPublicKey: |
    -----BEGIN PUBLIC KEY-----
    -----END PUBLIC KEY-----