{{- if .Values.aws.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.aws.storageClass.name }}
provisioner: {{ .Values.aws.storageClass.provisioner }}
volumeBindingMode: {{ .Values.aws.storageClass.volumeBindingMode }}
{{- with .Values.aws.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.aws.storageClass.allowedTopologies }}
allowedTopologies:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
