{{- if .Values.aws.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.aws.storageClass.name }}
provisioner: {{ .Values.aws.storageClass.provisioner }}
volumeBindingMode: {{ .Values.aws.storageClass.volumeBindingMode }}
{{- with .Values.aws.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 4 }}
{{- end }}

{{- if .Values.aws.storageClass.allowedTopologies -}}
allowedTopologies:
{{- range $k := .Values.aws.storageClass.allowedTopologies }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}

{{- end }}