{{- if and .Values.externalSecretsEnabled .Values.managementApp.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.managementApp.externalSecret.secretName | default "management-app-secret" }}
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.managementApp.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecret.secretStoreRef.name | default "aws-sm" }}
  target:
    name: {{ .Values.managementApp.externalSecret.secretName | default "management-app-secret" }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: MANAGEMENT_APP_MEMBER_ID
      remoteRef:
        key: {{ .Values.managementApp.externalSecret.awsSecretName | default "prod/management/app/creds" }}
        property: memberId
    - secretKey: MANAGEMENT_APP_PRIVATE_KEY
      remoteRef:
        key: {{ .Values.managementApp.externalSecret.awsSecretName | default "prod/management/app/creds" }}
        property: privateKey
{{- end }}
