{{- if .Values.networkPolicy.enabled -}}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.researchContainer.name }}-network-policy  
  annotations:
    description: "Research Container"
    version: "3.0.0-self-contained"
    architecture: "self-contained-dns"
    compliance: "management-api-audit-enabled"
    {{- if .Values.networkPolicy.logging }}
    logging: "enabled"
    {{- end }}
spec:
  selector: role == "{{ .Values.researchContainer.name }}"
  order: 10
  types:
    - Egress
  egress:
    - action: Allow
      protocol: UDP
      destination:
        namespaceSelector: kubernetes.io/metadata.name == "kube-system"
        selector: k8s-app == "kube-dns"
        ports:
          - 53

    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: kubernetes.io/metadata.name == "kube-system"
        selector: k8s-app == "kube-dns"
        ports:
          - 53
    
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: kubernetes.io/metadata.name in { "{{ .Release.Namespace }}" }
        selector: app == "{{ .Values.trustedOutputApp.name }}"
        ports:
          - {{ .Values.trustedOutputApp.service.targetPort }}

{{- end}}