{{- if .Values.setupApp.environmentVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.setupApp.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.setupApp.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.setupApp.name }}-sa
type: kubernetes.io/service-account-token
data:
    {{- if .Values.setupApp.environmentVariables.k8sApiServer }}
    k8s-api-server: {{ .Values.setupApp.environmentVariables.k8sApiServer | b64enc }}
    {{- end }}
    {{- if .Values.setupApp.environmentVariables.k8sServiceAccountPath }}
    k8s-service-account-path: {{ .Values.setupApp.environmentVariables.k8sServiceAccountPath | b64enc }}
    {{- end }}
    {{- if .Values.setupApp.environmentVariables.mgmtAppApiUrl }}
    mgmt-app-api-url: {{ .Values.setupApp.environmentVariables.mgmtAppApiUrl | b64enc }}
    {{- end }}
    {{- if .Values.setupApp.environmentVariables.mgmtAppMemberId }}
    mgmt-app-member-id: {{ .Values.setupApp.environmentVariables.mgmtAppMemberId | b64enc }}
    {{- end }}
    {{- if .Values.setupApp.environmentVariables.mgmtPublicKey }}
    mgmt-app-public-key: {{ .Values.setupApp.environmentVariables.mgmtPublicKey | b64enc }}
    {{- end }}
    {{- if .Values.setupApp.environmentVariables.mgmtPrivateKey }}
    mgmt-app-private-key: {{ .Values.setupApp.environmentVariables.mgmtPrivateKey | b64enc }}
    {{- end }}
{{- end }}