{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.setupApp.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.setupApp.service.type }}
  selector:
    app: {{ .Values.setupApp.name }}
  ports:
    - protocol: {{ .Values.setupApp.service.protocol }}
      port: {{ .Values.setupApp.service.port  }}
      targetPort: {{ .Values.setupApp.service.targetPort  }}
{{- end }}

