apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.setupApp.name }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.setupApp.name }}
  policyTypes:
    - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: data

