apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ .Values.setupApp.name }}-cluster-role
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}

rules: 
{{- range .Values.setupApp.clusterrole.rules }}
- apiGroups: 
  {{- range .apiGroups }}
    - {{ . | quote }}
  {{- end }}
  resources: 
  {{- range .resources }}
    - {{ . | quote }}
  {{- end }}
  resourceNames: 
  {{- range .resourceNames }}
    - {{ . | quote }}
  {{- end }}
  verbs: 
  {{- range .verbs }}
    - {{ . | quote}}
  {{- end }}
{{- end }}
