{{- if .Values.setupApp.environmentVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.setupApp.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.setupApp.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.setupApp.name }}-sa
type: kubernetes.io/service-account-token
data:
    {{- if .Values.setupApp.environmentVariables.k8sApiServer }}
    k8s-api-server: {{ .Values.setupApp.environmentVariables.k8sApiServer | b64enc }}
    {{- end }}
    {{- if .Values.setupApp.environmentVariables.k8sServiceAccountPath }}
    k8s-service-account-path: {{ .Values.setupApp.environmentVariables.k8sServiceAccountPath | b64enc }}
    {{- end }}
    {{- if .Values.managementApp.endpoint.host }}
    mgmt-app-api-url: {{ printf "%s://%s:%d" (default "https" .Values.managementApp.endpoint.protocol) .Values.managementApp.endpoint.host ((default 443 .Values.managementApp.endpoint.port) | int) | b64enc }}
    {{- end }}
    {{- if .Values.managementApp.memberId }}
    mgmt-app-member-id: {{ .Values.managementApp.memberId | b64enc }}
    {{- end }}
    {{- if .Values.managementApp.privateKey }}
    mgmt-app-private-key: {{ .Values.managementApp.privateKey | b64enc }}
    {{- end }}
{{- end }}