{{- if .Values.setupApp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.setupApp.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.setupApp.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.setupApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.setupApp.name }}
    spec:
      serviceAccountName: {{ .Values.setupApp.name }}-sa
      volumes:
        - name: {{ .Values.setupApp.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Values.setupApp.name }}-pvc
      containers:
      - name: {{ .Values.setupApp.image.repository }}
        image: {{ .Values.setupApp.image.registry }}/{{ .Values.setupApp.image.repository }}:{{ .Values.setupApp.image.tag }}
        {{- range .Values.setupApp.service.ports }}  
        ports:
          - containerPort: {{ .targetPort }}
        {{- end }}
        volumeMounts:
        - mountPath: "/opt/data"
          name: {{ .Values.setupApp.name }}-pv
        {{- if .Values.setupApp.workingDir }}
        workingDir: {{ .Values.setupApp.workingDir }}
        {{- end }}
        {{- if .Values.setupApp.command }}
        command: 
          {{- range .Values.setupApp.command }}
            - {{ . | quote }}
          {{- end }}
        {{- end}}
        env:
          - name: "DEPLOYMENT_ENVIRONMENT"
            value: "KUBERNETES"
        {{- if .Values.setupApp.environmentVariables.k8sApiServer }}
          - name: "K8S_APISERVER"
            value: {{ .Values.setupApp.environmentVariables.k8sApiServer }}
        {{- end }}
        {{- if .Values.setupApp.environmentVariables.k8sServiceAccountPath }}
          - name: "K8S_SERVICEACCOUNT_PATH"
            value: {{ .Values.setupApp.environmentVariables.k8sServiceAccountPath }}
        {{- end }}
         {{- if .Values.setupApp.environmentVariables.mgmtAppMemberId }}
          - name: "MANAGEMENT_APP_MEMBER_ID"
            value: {{ .Values.setupApp.environmentVariables.mgmtAppMemberId }}
        {{- end }}
        {{- if .Values.setupApp.environmentVariables.mgmtAppApiUrl }}
          - name: "MANAGEMENT_APP_API_URL"
            value: {{ .Values.setupApp.environmentVariables.mgmtAppApiUrl }}
        {{- end }}
        {{- if .Values.setupApp.environmentVariables.mgmtPublicKey }}
          - name: "MANAGEMENT_APP_PUBLIC_KEY"
            value: {{ .Values.setupApp.environmentVariables.mgmtPublicKey }}
        {{- end}}
        {{- if .Values.setupApp.environmentVariables.mgmtPrivateKey }}
          - name: "MANAGEMENT_APP_PRIVATE_KEY"
            value: {{ .Values.setupApp.environmentVariables.mgmtPrivateKey }}
        {{- end}}
        {{- if .Values.setupApp.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.setupApp.image.imagePullSecret  }}
      {{- end }}

   
{{- end }}