{{- if .Values.setupApp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.setupApp.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.setupApp.name }}
spec:
  serviceAccountName: {{ .Values.setupApp.name }}-sa
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.setupApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.setupApp.name }}
    spec:
      volumes:
        - name: {{ .Values.setupApp.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Values.setupApp.name }}-pvc
      containers:
      - name: {{ .Values.setupApp.image.repository }}
        image: {{ .Values.setupApp.image.registry }}/{{ .Values.setupApp.image.repository }}:{{ .Values.setupApp.image.tag }}
        
        {{- range .Values.setupApp.service.ports }}  
        ports:
          - containerPort: {{ .targetPort }}
        {{- end }}
        {{- if .Values.setupApp.workingDir }}
        workingDir: {{ .Values.setupApp.workingDir }}
        {{- end }}
        {{- if .Values.setupApp.command }}
        command: 
          {{- range .Values.setupApp.command }}
            - {{ . | quote }}
          {{- end }}
        {{- end}}
      {{- if .Values.setupApp.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.setupApp.image.imagePullSecret  }}
      {{- end }}
        volumeMounts:
        - mountPath: "/opt/data"
          name: {{ .Values.setupApp.name }}-pv
   
{{- end }}