apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.setupApp.name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
  {{- with .Values.setupApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 