apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "setup-app-sa" the role "setup-app-role" in the "safeinsights" namespace.
kind: RoleBinding
metadata:
  name: {{ .Values.setupApp.name }}-rb
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.setupApp.name }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.setupApp.name }}-role
  namespace: {{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
