apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "setup-app-sa" the role "setup-app-role" in the "safeinsights" namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.setupApp.name }}-crb
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.setupApp.name }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.setupApp.name }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
