{{- if .Values.setupApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.setupApp.name }}-sa
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
  {{- with .Values.setupApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
