apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "setup-app-sa" the role "setup-app-role" in the "safeinsights" namespace.
kind: RoleBinding
metadata:
  name: {{ .Values.setupApp.name }}-rb
subjects:
- kind: ServiceAccount
  name: {{ .Values.setupApp.name }}-sa
roleRef:
  kind: Role
  name: {{ .Values.setupApp.name }}-role
  apiGroup: rbac.authorization.k8s.io
