apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.setupApp.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.setupApp.service.type }}
  selector:
    app: {{ .Values.setupApp.service.name }}
{{- range .Values.setupApp.service.ports }}  
  ports:
    - protocol: {{- .protocol }}
      port: {{- .port }}
      targetPort: {{- .targetPort }}
{{- end }}