apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.trustedOutputApp.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.trustedOutputApp.service.type }}
  selector:
    app: {{ .Values.trustedOutputApp.service.name }}
{{- range .Values.trustedOutputApp.service.ports }}  
  ports:
    - protocol: {{- .protocol }}
      port: {{- .port }}
      targetPort: {{- .targetPort }}
{{- end }}