{{- if .Values.trustedOutputApp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.trustedOutputApp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.trustedOutputApp.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.trustedOutputApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.trustedOutputApp.name }}
    spec:
      {{- if .Values.trustedOutputApp.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.trustedOutputApp.image.imagePullSecret  }}
      {{- end }}
      volumes:
        {{- if .Values.trustedOutputApp.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-pvc" .Values.trustedOutputApp.name) .Values.trustedOutputApp.persistence.existingClaim }}
        {{- end }}
        {{- with .Values.volumes }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: {{ .Values.trustedOutputApp.image.repository }}
        imagePullPolicy: {{ .Values.trustedOutputApp.image.pullPolicy }}
        image: {{ .Values.trustedOutputApp.image.registry }}/{{ .Values.trustedOutputApp.image.repository }}:{{ .Values.trustedOutputApp.image.tag }}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi  
        ports:
          - containerPort: {{.Values.trustedOutputApp.service.targetPort}}
        {{- if .Values.trustedOutputApp.workingDir }}
        workingDir: {{ .Values.trustedOutputApp.workingDir }}
        {{- end }}
        {{- if .Values.trustedOutputApp.command }}
        command: 
          {{- range .Values.trustedOutputApp.command }}
            - {{ . | quote }}
          {{- end }}
        {{- end}}
        env:
        {{- if .Values.managementApp.memberId }}
          - name: "MANAGEMENT_APP_MEMBER_ID"
            value: {{ .Values.managementApp.memberId }}
        {{- end }}
          - name: "MANAGEMENT_APP_BASE_URL"
            valueFrom:
              secretKeyRef:
                name: enclave-secret
                key: management-app-api-url
          - name: "MANAGEMENT_APP_PRIVATE_KEY"
            valueFrom:
              secretKeyRef:
                name: enclave-secret
                key: management-app-private-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAffinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
