{{- if .Values.trustedOutputApp.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.trustedOutputApp.name }}-pvc
spec:
  accessModes: {{ .Values.trustedOutputApp.persistence.accessModes }}
  storageClassName: {{ .Values.trustedOutputApp.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.trustedOutputApp.persistence.pvcSize }}
{{- end }}

