{{- if .Values.trustedOutputApp.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Values.trustedOutputApp.name) .Values.trustedOutputApp.serviceAccount.name }}
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
  {{- with .Values.trustedOutputApp.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.trustedOutputApp.serviceAccount.automountServiceAccountToken | default false }}
{{- with .Values.trustedOutputApp.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- with .Values.trustedOutputApp.serviceAccount.secrets }}
secrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
