apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.trustedOutputApp.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.trustedOutputApp.service.type }}
  selector:
    app: {{ .Values.trustedOutputApp.name }}
  ports:
    - protocol: {{.Values.trustedOutputApp.service.protocol}}
      port: {{.Values.trustedOutputApp.service.port}}
      targetPort: {{.Values.trustedOutputApp.service.targetPort}}