{{- if .Values.trustedOutputApp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.trustedOutputApp.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.trustedOutputApp.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.trustedOutputApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.trustedOutputApp.name }}
    spec:
      volumes:
        - name: {{ .Values.trustedOutputApp.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Values.trustedOutputApp.name }}-pvc
      containers:
      - name: {{ .Values.trustedOutputApp.image.repository }}
        image: {{ .Values.trustedOutputApp.image.registry }}/{{ .Values.trustedOutputApp.image.repository }}:{{ .Values.trustedOutputApp.image.tag }}
        {{- range .Values.trustedOutputApp.service.ports }}  
        ports:
          - containerPort: {{ .targetPort }}
        {{- end }}
        volumeMounts:
        - mountPath: "/opt/data"
          name: {{ .Values.trustedOutputApp.name }}-pv
        {{- if .Values.trustedOutputApp.workingDir }}
        workingDir: {{ .Values.trustedOutputApp.workingDir }}
        {{- end }}
        {{- if .Values.trustedOutputApp.command }}
        command: 
          {{- range .Values.trustedOutputApp.command }}
            - {{ . | quote }}
          {{- end }}
        {{- end}}
        env:
        {{- if .Values.trustedOutputApp.environmentVariables.httpBasicAuth }}
          - name: "HTTP_BASIC_AUTH"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.trustedOutputApp.name }}-secret
                key: http-basic-auth
        {{- end }}
        {{- if .Values.trustedOutputApp.environmentVariables.mgmtAppMemberId }}
          - name: "MANAGEMENT_APP_MEMBER_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.trustedOutputApp.name }}-secret
                key: mgmt-app-member-id
        {{- end }}
        {{- if .Values.trustedOutputApp.environmentVariables.mgmtAppApiUrl }}
          - name: "MANAGEMENT_APP_API_URL"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.trustedOutputApp.name }}-secret
                key: mgmt-app-api-url
        {{- end }}
        {{- if .Values.trustedOutputApp.environmentVariables.mgmtPublicKey }}
          - name: "MANAGEMENT_APP_PUBLIC_KEY"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.trustedOutputApp.name }}-secret
                key: mgmt-app-public-key
        {{- end}}
        {{- if .Values.trustedOutputApp.environmentVariables.mgmtPrivateKey }}
          - name: "MANAGEMENT_APP_PRIVATE_KEY"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.trustedOutputApp.name }}-secret
                key: mgmt-app-private-key
        {{- end}}
      {{- if .Values.trustedOutputApp.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.trustedOutputApp.image.imagePullSecret  }}
      {{- end }}
          
      tolerations:
        - key: "environment"
          operator: "Equal"
          value: "production"
          effect: "NoSchedule"

{{- end }}

