{{- if .Values.trustedOutputApp.environmentVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.trustedOutputApp.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.trustedOutputApp.name }}
type: Opaque
data:
    {{- if .Values.trustedOutputApp.environmentVariables.httpBasicAuth }}
    http-basic-auth: {{ .Values.trustedOutputApp.environmentVariables.httpBasicAuth | b64enc }}
    {{- end }}
    {{- if .Values.trustedOutputApp.environmentVariables.mgmtAppApiUrl }}
    mgmt-app-api-url: {{ .Values.trustedOutputApp.environmentVariables.mgmtAppApiUrl | b64enc }}
    {{- end }}
    {{- if .Values.trustedOutputApp.environmentVariables.mgmtAppMemberId }}
    mgmt-app-member-id: {{ .Values.trustedOutputApp.environmentVariables.mgmtAppMemberId | b64enc }}
    {{- end }}
    {{- if .Values.trustedOutputApp.environmentVariables.mgmtPublicKey }}
    mgmt-app-public-key: {{ .Values.trustedOutputApp.environmentVariables.mgmtPublicKey | b64enc }}
    {{- end }}
    {{- if .Values.trustedOutputApp.environmentVariables.mgmtPrivateKey }}
    mgmt-app-private-key: {{ .Values.trustedOutputApp.environmentVariables.mgmtPrivateKey | b64enc }}
    {{- end }}
{{- end }}