# Not using a cluster role becuase we do not want these permissions to be cluster scoped
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: setup-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  # I do not think the wildcard here works, but we want to limit this control to only RC pods
  resourceNames: ["research-container-*"]
  verbs: ["get", "watch", "list", "create", "delete"]
