apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "setup-app-sa" the role "setup-app-role" in the "safeinsights" namespace.
kind: RoleBinding
metadata:
  name: setup-app-rb
  namespace: safeinsights
subjects:
- kind: ServiceAccount
  name: setup-app-sa
  namespace: safeinsights
roleRef:
  kind: Role
  name: setup-app-role
  apiGroup: rbac.authorization.k8s.io
