# Service account the Setup Runs to be able to launch the research pods
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: setup-app-sa
  namespace: safeinsights