{{- if .Values.aws.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.aws.storageClass.name }}
  {{- with .Values.aws.storageClass.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
provisioner: {{ .Values.aws.storageClass.provisioner }}
{{- with .Values.aws.storageClass.reclaimPolicy }}
reclaimPolicy: {{ . }}
{{- end }}
volumeBindingMode: {{ .Values.aws.storageClass.volumeBindingMode }}
{{- with .Values.aws.storageClass.mountOptions }}
mountOptions:
{{ toYaml . | indent 2 }}
{{- end }}
{{- with .Values.aws.storageClass.parameters }}
parameters:
{{ toYaml . | indent 2 }}
{{- end }}
{{- if .Values.aws.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.aws.storageClass.allowVolumeExpansion }}
{{- end }}
{{- with .Values.aws.storageClass.allowedTopologies }}
allowedTopologies:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}

