apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: internal-auth-credentials
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: internal-auth-credentials
    creationPolicy: Owner
  data:
    - secretKey: INTERNAL_BASIC_AUTH
      remoteRef:
        key: prod/enclave/internal-auth
        property: internalBasicAuth
