{{- if .Values.setupApp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.setupApp.name }}-svc
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
  {{- with .Values.setupApp.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.setupApp.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.setupApp.name }}
  ports:
    - name: {{ .Values.setupApp.service.portName | default "http" }}
      protocol: {{ .Values.setupApp.service.protocol | default "TCP" }}
      port: {{ required "setupApp.service.port is required" .Values.setupApp.service.port }}
      targetPort: {{ .Values.setupApp.service.targetPort | default (.Values.setupApp.service.portName | default .Values.setupApp.service.port) }}
{{- end }}

