{{- if .Values.setupApp.persistence.enabled -}}                 {{/* Only render when persistence is enabled */}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.setupApp.name }}-pvc
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
  {{- with .Values.setupApp.persistence.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
{{ toYaml .Values.setupApp.persistence.accessModes | indent 4 }}  # e.g., ["ReadWriteOnce"] for EBS
  storageClassName: {{ .Values.setupApp.persistence.storageClassName | quote }}
  {{- with .Values.setupApp.persistence.volumeMode }}
  volumeMode: {{ . }}                                            # default is Filesystem; set if you need Block
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.setupApp.persistence.pvcSize | quote }} # e.g., "20Gi"
{{- end }}

