{{- if and (.Values.externalSecretsEnabled | default true) (.Values.setupApp.secret.enabled | default true) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.setupApp.secret.name }}
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.setupApp.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecret.secretStoreRef.name | default "aws-sm" }}
  target:
    name: {{ .Values.setupApp.secret.name }}
    creationPolicy: Owner
data:
  - secretKey: SETUP_APP_BASIC_AUTH        
    remoteRef:
      key: {{ .Values.setupApp.externalSecret.awsSecretName }}
      property: setupAppBasicAuth           
  - secretKey: SETUP_APP_MEMBER_ID         
    remoteRef:
      key: {{ .Values.setupApp.externalSecret.awsSecretName }}
      property: setupAppMemberId          
{{- end }}
