{{- if and (.Values.externalSecretsEnabled | default true) (.Values.trustedOutputApp.secret.enabled | default true) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.trustedOutputApp.secret.name }}
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.trustedOutputApp.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecret.secretStoreRef.name | default "aws-sm" }}
  target:
    name: {{ .Values.trustedOutputApp.secret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  {{- if .Values.trustedOutputApp.secret.data }}
  data:
    - secretKey: TOA_SIGNING_KEY
      remoteRef:
        key: {{ .Values.trustedOutputApp.externalSecret.awsSecretName }}
        property: signingKey
    - secretKey: TOA_BASIC_AUTH
      remoteRef:
        key: {{ .Values.trustedOutputApp.externalSecret.awsSecretName }}
        property: toaBasicAuth
  {{- end }}
{{- end }}

