{{- if .Values.trustedOutputApp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.trustedOutputApp.name }}-svc
  namespace: {{ .Values.adminNamespace | default "enclave-admin-ns" }}
  labels:
    {{- include "secure-enclave.labels" . | nindent 4 }}
  {{- with .Values.trustedOutputApp.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.trustedOutputApp.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.trustedOutputApp.name }}
  ports:
    - name: {{ .Values.trustedOutputApp.service.portName | default "http" }}
      protocol: {{ .Values.trustedOutputApp.service.protocol | default "TCP" }}
      port: {{ .Values.trustedOutputApp.service.port }}
      # If targetPort not set, default to named port; else fall back to the same number as 'port'
      targetPort: {{ .Values.trustedOutputApp.service.targetPort | default (.Values.trustedOutputApp.service.portName | default .Values.trustedOutputApp.service.port) }}
{{- end }}


