setupApp:
  image: 
    registry: 
    repository: nginx
    imagePullSecret: 
  environmentVariables:
    mgmtPrivateKey: |
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----
    mgmtPublicKey: |
        -----BEGIN PUBLIC KEY-----
        -----END PUBLIC KEY-----
trustedOutputApp:
  image: 
    registry: 
    repository: nginx
    imagePullSecret: 
  environmentVariables:
    mgmtPrivateKey: |
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----
    mgmtPublicKey: |
        -----BEGIN PUBLIC KEY-----
        -----END PUBLIC KEY-----