#!/bin/bash

set -euo pipefail

say() {
	echo -e "${@}"
}

fail() {
	say "${@}" 1>&2
	exit 1
}
DOCKER_AUTH_FILE="$1"
if [[ ! -r "$DOCKER_AUTH_FILE" ]]; then
  echo "Cannot read file: $DOCKER_AUTH_FILE" >&2
  exit 1
fi
HARBOR_USERNAME=$(jq -r ".name" "$DOCKER_AUTH_FILE")
HARBOR_PASSWORD=$(jq -r ".secret" "$DOCKER_AUTH_FILE")
SERVER_ENDPOINT=$(jq -r ".serveraddress" "$DOCKER_AUTH_FILE")
for var in HARBOR_USERNAME HARBOR_PASSWORD SERVER_ENDPOINT; do
	echo "${!var}"
  # ${!var} expands to the value of the variable whose name is stored in $var
  if [[ -z "${!var:-}" || "${!var}" == "null"  ]]; then
    echo "Error: $var is missing or empty" >&2
    exit 1
  fi
done
NAMESPACE="${NAMESPACE:-default}"
K8S_SECRET="${K8S_SECRET:-si-docker-config}"
SETUP_APP_SA="${SETUP_APP_SA:-setup-app-sa}"
say "Running Docker login for ${SERVER_ENDPOINT}..."
echo "$HARBOR_PASSWORD" | docker login "$SERVER_ENDPOINT" --username "$HARBOR_USERNAME" --password-stdin
RC=${?}
[ ${RC} -eq 0 ] || exit ${RC}

if kubectl get node &>/dev/null ; then
    DOCKER_CONFIG="$(readlink -f ~/.docker/config.json 2>/dev/null)"
	if [ -n "${DOCKER_CONFIG}" ] && [ -f "${DOCKER_CONFIG}" ] ; then
		say "Creating Kubernetes secret (${K8S_SECRET}) for [${DOCKER_CONFIG}]..."
        while read -r NS ; do
			[ "${NS}" == "default" ] || [ "${NS}" == "${NAMESPACE}" ] || kubectl get secret -n "${NS}" "${K8S_SECRET}" &>/dev/null || continue
			say "\tCreating on namespace ${NS}..."
			kubectl delete secret \
				--namespace "${NS}" \
				"${K8S_SECRET}" &>/dev/null || true
			kubectl create secret \
				generic \
				--namespace "${NS}" \
				"${K8S_SECRET}" \
				--from-file=.dockerconfigjson="${DOCKER_CONFIG}" \
				--type=kubernetes.io/dockerconfigjson || fail "ERROR: Failed to create the secret ${K8S_SECRET} in namespace ${NS} (${?})"
			echo "Patching the service account to use the secret..."
			kubectl patch serviceaccount  \
				--namespace "${NAMESPACE}" "${SETUP_APP_SA}" \
				-p "{\"imagePullSecrets\": [{\"name\": \"${K8S_SECRET}\"}]}" || fail "ERROR: Failed to patch the service account ${K8S_SECRET} (${?})"
		done < <(kubectl get namespace | awk '{ print $1 }' | tail -n +2 | sort)
    fi
fi
say "Done."
exit 0