# Default values for secure-enclave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

## @param aws this defines the values configured when deployed on AWS.
##
aws:
  ## @param aws.enabled this defines if AWS configurations are enabled.
  ##
  enabled: false
  ## @param aws.storageClass this defines the storage class used for the deployment
  ##
  storageClass:
    ## @param aws.storageClass.name this defines the name of the storage class
    ##
    name: aws-ebs-sc
    ## @param aws.storageClass.provisioner this defines the storage class provisioner
    ##
    provisioner: ebs.csi.aws.com
    ## @param aws.storageClass.volumeBindingMode this defines the storage class volume binding mode
    ##
    volumeBindingMode: WaitForFirstConsumer
    ## @param aws.storageClass.parameters this defines the storage class parameters
    ##
    parameters:
      ## @param aws.storageClass.parameters.csi.storage.k8s.io/fstype this defines the filesystem type for the storage class
      ##
      csi.storage.k8s.io/fstype: xfs
      ## @param aws.storageClass.parameters.type this defines the type of the storage class
      ##
      type: io1
      ## @param aws.storageClass.parameters.iopsPerGB this defines the IOPS per GB for the storage
      ##
      iopsPerGB: "50"
      ## @param aws.storageClass.parameters.encrypted  this defines if the storage is encrypted
      ##
      encrypted: "true"
    ## @params aws.storageClass.allowedTopologies this defines the allowed toplogies, for eg. the zone where the storage class will be created in.
    ##
    allowedTopologies:
      - matchLabelExpressions:
          - key: topology.ebs.csi.aws.com/zone
            values:
              - us-east-1

## @param networkPolicy this defines if the network policy restrictions are enforced.
## Few limitations:
## FQDNs Egress restrictions
## TODO. Enforce Ingress only to some pods
##
networkPolicy:
  ## @param networkPolicy.enabled this enables or  disables the network policy
  enabled: true
  logging: true
  ## @param networkPolicy.installCalico this enables or disables automatic installation of Calico
  installCalico: false

## @param managementApp this defines all the configurations related to the management app
##
managementApp:
  ## @param managementApp.memberId this defines the id of the member deploying the enclave
  ##
  memberId:
  ## @param managementApp.endpoint this defines the endpoint where the management app is available.
  ##
  endpoint: https://app.safeinsights.org
## @param setupApp this defines the setup app configuration
##
setupApp:
  ## @param setupApp.enabled this defines if the setup app should be deployed
  ##
  enabled: true
  ## @param setupApp.name this defines the name of the deployment and containers for the setup app
  ##
  name: setup-app
  ## @param setupApp.serviceAccount this defines the service account used by setup account to manage the research container and also access the Kubernetes API
  ##
  serviceAccount:
    annotations:
      kubernetes.io/enforce-mountable-secrets: "true"
  ## @param setupApp.persistence this defines the persistence configuration for the setup app.
  ##
  persistence:
    ## @param setupApp.persistence.enabled this defines if the persistence should be enabled during the deployment
    ##
    enabled: false
    ## @param setupApp.persistence.storageClassName this defines the storageClassName used for the persitence
    ##
    storageClassName: aws-ebs-sc
    ## @param setupApp.persistence.pvcSize this defines the size set for the the persitence
    ##
    pvcSize: 1Gi
    ## @param setupApp.persistence.accessModes this defines the access modes used for the persitence
    ##
    accessModes:
      - ReadWriteOnce
  ## @param setupApp.service this defines the service on which the setup App will be accessible
  ##
  service:
    ## @param setupApp.service.type this defines the service type
    ##
    type: ClusterIP
    ## @param setupApp.service.protocol this defines the service protocol
    ##
    protocol: TCP
    ## @param setupApp.service.port this defines the service external port
    ##
    port: 5051
    ## @param setupApp.service.targetPort this defines the container internal port that the service redirects to.
    ##
    targetPort: 5051
  ## @param setupApp.image this defines the image configuration for the setup app
  ##
  image:
    ## @param setupApp.image.registry this defines the image registry
    ##
    registry: harbor.safeinsights.org/safeinsights-public
    ## @param setupApp.image.repository this defines the image repository
    ##
    repository: setup-app
    ## @param setupApp.image.tag this defines the image tag
    ##
    tag: 20251006-e1ccae88
    ## @param setupApp.image.pullPolicy this defines the image pull policy
    ##
    pullPolicy: Always
  ## @param setupApp.workingDir this defines the working directory inside the setup app container
  ##
  workingDir: /home/node/code
  ## @param setupApp.command this defines the command to start the setup app container
  ##
  command: ["npx", "tsx", "src/scripts/poll.ts"]
  ## @param setupApp.environmentVariables this defines the setup app environment variables
  ##
  environmentVariables:
    ## @param setupApp.environmentVariables.harborPullSecret this configures the pull secret from harbor
    ##
    harborPullSecret: si-docker-config
    ## @param setupApp.environmentVariables.pollIntervall this overrides the setup app polling interval
    ##
    pollIntervall: "60000"
## @param trustedOutputApp this defines the trusted output app configuration
##
trustedOutputApp:
  ## @param trustedOutputApp.enabled this defines if the trusted output app should be deployed
  ##
  enabled: true
  ## @param trustedOutputApp.name this defines the name of the deployment and containers for the trusted output app
  ##
  name: toa
  ## @param trustedOutputApp.persistence this defines the persistence configuration for the trusted output app.
  ##
  persistence:
    ## @param trustedOutputApp.persistence.enabled this defines if the persistence should be enabled during the deployment
    ##
    enabled: false
    ## @param trustedOutputApp.persistence.storageClassName this defines the storageClassName used for the persitence
    ##
    storageClassName: aws-ebs
    ## @param trustedOutputApp.persistence.pvcSize this defines the size set for the the persitence
    ##
    pvcSize: 1Gi
    ## @param trustedOutputApp.persistence.accessModes this defines the access modes used for the persitence
    ##
    accessModes:
      - ReadWriteOnce
  ## @param trustedOutputApp.service this defines the service on which the trusted output App will be accessible
  ##
  service:
    ## @param trustedOutputApp.service.type this defines the service type
    ##
    type: ClusterIP
    ## @param trustedOutputApp.service.protocol this defines the service protocol
    ##
    protocol: TCP
    ## @param trustedOutputApp.service.port this defines the service external port
    ##
    port: 5050
    ## @param trustedOutputApp.service.targetPort this defines the container internal port that the service redirects to.
    ##
    targetPort: 3002
  ## @param trustedOutputApp.image this defines the image configuration for the trusted output app
  ##
  image:
    ## @param trustedOutputApp.image.registry this defines the image registry
    ##
    registry: harbor.safeinsights.org/safeinsights-public
    ## @param trustedOutputApp.image.repository this defines the image repository
    ##
    repository: trusted-output-app
    ## @param trustedOutputApp.image.tag this defines the image tag
    ##
    tag: 20250728-a5d087fc
    ## @param trustedOutputApp.image.pullPolicy this defines the image pull policy
    ##
    pullPolicy: Always
  ## @param trustedOutputApp.workingDir this defines the working directory inside the setup app container
  ##
  workingDir: /home/node/app
  ## @param trustedOutputApp.command this defines the command to start the trusted output app container
  ##
  command: ["npm", "run", "start"]
## @param researchContainer this defines the research container app configuration
##
researchContainer:
  ## @param researchContainer.name this defines the name of the jobs and containers for the research
  ##
  name: research

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  {}
# This is for setting Kubernetes Pod Affinity rules.
# For more information checkout: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
podAffinity: {}
