# Default values for secure-enclave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# -- This defines the values configured when deployed on AWS.
aws:
  # -- Sets if AWS configurations are enabled.
  enabled: false
  # -- Sets the storage class used for the deployment
  storageClass:
    # -- Sets the name of the storage class
      name: aws-ebs-sc
    # -- Sets the storage class provisioner
      provisioner: ebs.csi.aws.com
    # -- Sets the storage class volume binding mode
      volumeBindingMode: WaitForFirstConsumer
    # -- Sets the storage class parameters
      parameters:
      # -- Sets the filesystem type for the storage class
          csi.storage.k8s.io/fstype: xfs
      # -- Sets the type of the storage class
          type: io1
      # -- Sets the IOPS per GB for the storage
          iopsPerGB: "50"
      # -- Sets if the storage is encrypted
          encrypted: "true"
    # -- Sets the allowed toplogies, for eg. the zone where the storage class will be created in.
      allowedTopologies:
      - matchLabelExpressions:
          - key: topology.ebs.csi.aws.com/zone
            values:
              - us-east-1

# -- Sets if the network policy restrictions are enforced.
networkPolicy:
  # -- networkPolicy.enabled this enables or  disables the network policy
  enabled: true
  logging: true
  # -- networkPolicy.installCalico this enables or disables automatic installation of Calico
  installCalico: false

# -- Sets all the configurations related to the management app
managementApp:
  # -- Sets the id of the member deploying the enclave
  memberId:
  # -- Sets the endpoint where the management app is available.
  endpoint: https://app.safeinsights.org
# -- Sets the setup app configuration
setupApp:
  # -- Sets if the setup app should be deployed
  enabled: true
  # -- Sets the name of the deployment and containers for the setup app
  name: setup-app
  # -- Sets the service account used by setup account to manage the research container and also access the Kubernetes API
  serviceAccount:
    annotations:
      kubernetes.io/enforce-mountable-secrets: "true"
  # -- Sets the persistence configuration for the setup app.
  persistence:
    # -- Sets if the persistence should be enabled during the deployment
      enabled: false
    # -- Sets the storageClassName used for the persitence
      storageClassName: aws-ebs-sc
    # -- Sets the size set for the the persitence
      pvcSize: 1Gi
    # -- Sets the access modes used for the persitence
      accessModes:
      - ReadWriteOnce
  # -- Sets the service on which the setup App will be accessible
  service:
    # -- Sets the service type
      type: ClusterIP
    # -- Sets the service protocol
      protocol: TCP
    # -- Sets the service external port
      port: 5051
    # -- Sets the container internal port that the service redirects to.
      targetPort: 5051
  # -- Sets the image configuration for the setup app
  image:
    # -- Sets the image registry
      registry: harbor.safeinsights.org/safeinsights-public
    # -- Sets the image repository
      repository: setup-app
    # -- Sets the image tag
      tag: 20251006-e1ccae88
    # -- Sets the image pull policy
      pullPolicy: Always
  # -- Sets the working directory inside the setup app container
  workingDir: /home/node/code
  # -- Sets the command to start the setup app container
  command: ["npx", "tsx", "src/scripts/poll.ts"]
  # -- Sets the setup app environment variables
  environmentVariables:
    # -- setupApp.environmentVariables.harborPullSecret this configures the pull secret from harbor
      harborPullSecret: si-docker-config
    # -- setupApp.environmentVariables.pollIntervall this overrides the setup app polling interval
      pollIntervall: "60000"
# -- Sets the trusted output app configuration
trustedOutputApp:
  # -- Sets if the trusted output app should be deployed
  enabled: true
  # -- Sets the name of the deployment and containers for the trusted output app
  name: toa
  # -- Sets the persistence configuration for the trusted output app.
  persistence:
    # -- Sets if the persistence should be enabled during the deployment
      enabled: false
    # -- Sets the storageClassName used for the persitence
      storageClassName: aws-ebs
    # -- Sets the size set for the the persitence
      pvcSize: 1Gi
    # -- Sets the access modes used for the persitence
      accessModes:
      - ReadWriteOnce
  # -- Sets the service on which the trusted output App will be accessible
  service:
    # -- Sets the service type
      type: ClusterIP
    # -- Sets the service protocol
      protocol: TCP
    # -- Sets the service external port
      port: 5050
    # -- Sets the container internal port that the service redirects to.
      targetPort: 3002
  # -- Sets the image configuration for the trusted output app
  image:
    # -- Sets the image registry
      registry: harbor.safeinsights.org/safeinsights-public
    # -- Sets the image repository
      repository: trusted-output-app
    # -- Sets the image tag
      tag: 20250728-a5d087fc
    # -- Sets the image pull policy
      pullPolicy: Always
  # -- Sets the working directory inside the setup app container
  workingDir: /home/node/app
  # -- Sets the command to start the trusted output app container
  command: ["npm", "run", "start"]
# -- Sets the research container app configuration
##
researchContainer:
  # -- Sets the name of the jobs and containers for the research
  name: research

# -- This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# -- This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  {}
# This is for setting Kubernetes Pod Affinity rules.
# For more information checkout: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
podAffinity: {}
