name: "Publish charts to repo"
on:
  push:
    branches:
      - main
    paths:
      - "secure-enclave/Chart.yaml"
      - "secure-enclave/values.yaml"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Remove ci-values from chart package
        run: rm -rf ./secure-enclave/ci

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: secure-enclave
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"